config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: "registrations" }

  root to: 'pages#home'
  get '/calendar', to: 'pages#calendar'

  get '/accidents/confirm', to: 'accidents#confirm'
  post '/accidents/send', to: 'accidents#send_accident'
  post '/workdays/send', to: 'workdays#send_worklog'
  post '/payslips/send', to: 'payslips#send_payslip'
  post '/users/send', to: 'users#send_ipa'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :accidents do
    member do
      get :new3
      get :complete
    end
  end

  get '/onboarding', to: 'users#onboarding', as: 'onboarding'
  get '/landing', to: 'pages#landing'
  patch '/contract_update', to: 'users#contract_update', as: 'contract_update'
  get '/personal_details', to: 'users#personal_details', as: 'personal_details'
  patch '/personal_update', to: 'users#personal_update', as: 'personal_update'
  resources :users
  resources :workdays, only: [:new, :create, :edit, :update]
  get 'workdays/on_leave', to: 'workdays#on_leave'
  get 'workdays/on_leave/:id', to: 'workdays#on_leave'
  get 'workdays/working/:id', to: 'workdays#working'
  get 'organisation', to: 'organisations#index'
  get 'faq', to: 'organisations#faq'
  resources :payslips, only: [:new, :create, :edit, :update]
  get '/files', to: 'pages#files'
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable, :recoverable, :rememberable, authentication_keys: [:phone_number]
  has_many :payslips, dependent: :destroy
  has_many :accidents, dependent: :destroy
  has_many :workdays, dependent: :destroy
  has_one_attached :ipa_photo

  has_many :notifications, as: :recipient

  validates :phone_number, presence: true, uniqueness: true, format: { with: /\A[689]\d{7}\z/ }
  validates_presence_of :password
  validates_confirmation_of :password
  validates_length_of :password, minimum: 6, too_short: 'Your password should be at least 6 characters long'


  def email_required?
    false
  end

  def email_changed?
    false
  end

  def will_save_change_to_email?
    false
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def onboarding
    render layout: "nonav"
  end

  def contract_update
    # ipa = params[:user][:ipa_photo]
    # if defined?(params[:user][:ipa_photo].content_type) == nil
    #   base_64_image = ipa.gsub!(/^data:.*,/, '')
    #   decoded_image = Base64.decode64(base_64_image)

    #   current_user.ipa_photo.attach(
    #     io: StringIO.new(decoded_image),
    #     filename: "contract_#{current_user.email}.png"
    #     )
    #   if current_user.update(strong_params)
    #     redirect_to :personal_details
    #   else
    #     render :onboarding
    #   end
    # else
    #   # if current_user.update(strong_upload_params)
    #   #   redirect_to :personal_details
    #   # else
    #   #   render :onboarding
    #   # end
    # end
    unless strong_upload_params[:ipa_photo].nil?
      current_user.ipa_photo = strong_upload_params[:ipa_photo]
      current_user.save(validate: false)
    end
    redirect_to :personal_details
  end

  def personal_details
  end

  def personal_update
    current_user.name = personal_params[:name]
    current_user.basic_salary = personal_params[:basic_salary]
    current_user.save(validate: false)
    redirect_to root_path
  end

  def send_ipa
    @user = current_user
    @email = params.permit(:email)[:email]
    if @email.match(/\A([\w+\-].?)+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i)
      UserMailer.with(user: @user, email: @email).send_ipa.deliver_now
    else
      flash.alert = "Not an appropriate email"
    end
  end

  private

  def strong_params
    params.require(:user).permit(:name,:phone_number,:identification_number,:name,:basic_salary,:hourly_salary)
  end
  def strong_upload_params
    params.require(:user).permit(:ipa_photo)
  end
  def personal_params
    params.require(:user).permit(:name,:basic_salary)
  end
end

app/views/users/onboarding.html.erb
<%= turbo_frame_tag "edit-profile" do %>
<div class="container" id="capture">
  <div class="bg-secondary mt-5 d-flex w-100 justify-content-between align-items-center" style="height:5px">
    <div class="btn-green rounded-circle text-center" style="height: 50px; width: 50px; line-height: 50px"> <p class="align-middle text-white">1</p>  </div>
    <div class="btn-green rounded-circle text-center" style="height: 50px; width: 50px; line-height: 50px"> <p class="text-white">2</p> </div>
    <div class="bg-dark rounded-circle text-center" style="height: 50px; width: 50px; line-height: 50px"> <p class="text-secondary">3</p> </div>
  </div>
  <br><br>
  <h2 class ="text-center">Photo of your IPA</h2>
  <%= simple_form_for current_user, url: 'contract_update' do |f| %>
    <%= f.input :ipa_photo, label: 'This document is important for checking your salary and making claims.' %>
    <%= f.button :submit, class: 'btn btn-blue btn-block text-white', value: 'Upload' %>
  <% end %>

  <%= link_to 'Skip', personal_details_path, class: 'btn btn-outline-primary text-primary btn-block my-3' %>
  <% end %>
</div>

</div>

</div>

app/views/users/personal_details.html.erb
<%= turbo_frame_tag 'edit-profile' do %>
<div class="container">
  <div class="bg-secondary mt-5 d-flex w-100 justify-content-between align-items-center" style="height:5px">
    <div class="btn-green rounded-circle text-center" style="height: 50px; width: 50px; line-height: 50px"> <p class="align-middle text-white">1</p>  </div>
    <div class="btn-green rounded-circle text-center" style="height: 50px; width: 50px; line-height: 50px"> <p class="text-white">2</p> </div>
    <div class="btn-green rounded-circle text-center" style="height: 50px; width: 50px; line-height: 50px"> <p class="text-white">3</p> </div>
  </div>
  <br><br>
  <h2 class ="text-center text-blue">Personal details</h2>
  <%= simple_form_for current_user, url: 'personal_update', data: { turbo_frame: '_top' } do |f| %>
  <%= f.input :name %>
  <%= f.input :basic_salary, label: 'Basic Monthly Salary (in SGD)',
    hint: "This is used to calculate your pay for overtime work and work on rest days, which is important in salary claims." %>
  <%= f.button :submit, class: 'btn btn-blue btn-block text-white', value: 'Submit' %>
  <% end %>
  <%= link_to 'Back', :back, class: 'btn btn-outline-primary text-primary btn-block my-3' %>
</div>
  <% end %>

app/views/users/send_ipa.html.erb
<%= turbo_frame_tag "ipa_email" do %>
<div class="border p-3 my-3">
  <h4>Send IPA as email</h4>
  <p>Email is on the way!</p>
</div>
<% end %>