config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: "registrations" }

  root to: 'pages#home'
  get '/calendar', to: 'pages#calendar'

  get '/accidents/confirm', to: 'accidents#confirm'
  post '/accidents/send', to: 'accidents#send_accident'
  post '/workdays/send', to: 'workdays#send_worklog'
  post '/payslips/send', to: 'payslips#send_payslip'
  post '/users/send', to: 'users#send_ipa'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :accidents do
    member do
      get :new3
      get :complete
    end
  end

  get '/onboarding', to: 'users#onboarding', as: 'onboarding'
  get '/landing', to: 'pages#landing'
  patch '/contract_update', to: 'users#contract_update', as: 'contract_update'
  get '/personal_details', to: 'users#personal_details', as: 'personal_details'
  patch '/personal_update', to: 'users#personal_update', as: 'personal_update'
  resources :users
  resources :workdays, only: [:new, :create, :edit, :update]
  get 'workdays/on_leave', to: 'workdays#on_leave'
  get 'workdays/on_leave/:id', to: 'workdays#on_leave'
  get 'workdays/working/:id', to: 'workdays#working'
  get 'organisation', to: 'organisations#index'
  get 'faq', to: 'organisations#faq'
  resources :payslips, only: [:new, :create, :edit, :update]
  get '/files', to: 'pages#files'
end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert" style="z-index: 5000; top:0;max-height:66px; margin-top:10px;">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert" style="z-index: 5000; top:0; max-height:66px; margin-top:10px;">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_loading.html.erb
<% tips = ['You can only claim up to 1 year 📆 of unpaid salary 💸',
  'Airport police 👮 can help you to stay in Singapore to make a complaint if boss forces you to fly home ✈️',
  'Boss must pay you 💵 even if he does not give you work ❌',
  'You should be paid 1.5x 💵💵 your hourly pay if you work overtime (more than 44h per week) 🕚'] %>

<div class="spinner bg-primary fixed-top">
  <div style="text-align:center;">
  <div class="spinner-border text-light" role="status">
    <span class="sr-only">Loading...</span>
  </div>
  <h4 class="mt-5 text-info">💡 Did you know?</h4>
  <h4 class="mx-5 mb-5 text-light"><%= tips.sample %></h4>
  </div>
</div>

app/views/shared/_navbar.html.erb
<%
=begin%>
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to "#", class: "navbar-brand" do %>
  <%= image_tag "https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/logo.png" %>
  <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
      <li class="nav-item active">
        <%= link_to "Home", "#", class: "nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to "Messages", "#", class: "nav-link" %>
      </li>
      <li class="nav-item dropdown">
        <%= image_tag "https://kitt.lewagon.com/placeholder/users/ssaunier", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
          <%= button_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
        </div>
      </li>
      <% else %>
      <li class="nav-item">
        <%= link_to "Login", new_user_session_path, class: "nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to "Sign up", new_user_registration_path, class: "nav-link" %>
      </li>
      <% end %>
    </ul>
  </div>
</div>
<%
=end%>

<%= %>
<nav class="navbar fixed-bottom navbar-light bg-light pb-0">
  <div class="container d-flex justify-around">
    <%= link_to root_path, data: { turbo: false }, class: 'text-center' do %>
    <i class="fas fa-house-user fa-2x"></i><br>
    Home
    <% end %>
    <%= link_to calendar_path, data: { turbo: false }, class: 'text-center' do %>
    <i class="far fa-calendar-alt fa-2x"></i><br>
    Calendar
    <% end %>
    <%= link_to files_path, data: { turbo: false }, class: 'text-center' do %>
    <i class="far fa-file-alt fa-2x"></i><br>
    Files
    <% end %>
    <%= link_to organisation_path, data: { turbo: false }, class: 'text-center' do %>
    <i class="far fa-question-circle fa-2x"></i><br>
    Help
    <% end %>
    <%
=begin%>
 <%= link_to root_path, data: { turbo: false }, class: 'text-center' do %>
    <i class="fas fa-sign-out-alt fa-2x"></i><br>
    Logout
    <% end %>
<%
=end%>
  </div>
</nav>
<% %>