config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: "registrations" }

  root to: 'pages#home'
  get '/calendar', to: 'pages#calendar'

  get '/accidents/confirm', to: 'accidents#confirm'
  post '/accidents/send', to: 'accidents#send_accident'
  post '/workdays/send', to: 'workdays#send_worklog'
  post '/payslips/send', to: 'payslips#send_payslip'
  post '/users/send', to: 'users#send_ipa'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :accidents do
    member do
      get :new3
      get :complete
    end
  end

  get '/onboarding', to: 'users#onboarding', as: 'onboarding'
  get '/landing', to: 'pages#landing'
  patch '/contract_update', to: 'users#contract_update', as: 'contract_update'
  get '/personal_details', to: 'users#personal_details', as: 'personal_details'
  patch '/personal_update', to: 'users#personal_update', as: 'personal_update'
  resources :users
  resources :workdays, only: [:new, :create, :edit, :update]
  get 'workdays/on_leave', to: 'workdays#on_leave'
  get 'workdays/on_leave/:id', to: 'workdays#on_leave'
  get 'workdays/working/:id', to: 'workdays#working'
  get 'organisation', to: 'organisations#index'
  get 'faq', to: 'organisations#faq'
  resources :payslips, only: [:new, :create, :edit, :update]
  get '/files', to: 'pages#files'
end

app/views/pages/calendar.html.erb
<div class="container my-3 scrollable">
  <%= month_calendar(events: @workdays) do |date, workdays| %>
    <% if workdays.empty? %>
      <%= link_to "#{new_workday_path}?#{date}" do %>
        <%= date.day %>
      <% end %>
    <% else %>
      <% workdays.each do |workday| %>
        <div>
          <%= link_to "#{edit_workday_path(workday)}?#{date}" do %>
          <% if workday.on_rest %>
            <div class="calendar-circle date" style="background-color: rgb(254, 214, 72, 0.4);"><%= date.day %></div>
          <% elsif workday.on_mc %>
            <div class="calendar-circle date" style="background-color: rgba(241, 98, 81, 0.4);"><%= date.day %></div>
          <% else %>
            <div class="d-flex calendar-circle date" style="background-color: rgba(27, 187, 164, 0.4);"><%= date.day %></div>
            <% end %>
          <% end %>
        </div>
      <% end %>
    <% end %>
  <% end %>
  <!-- legend -->
  <div class="d-flex justify-content-around">
    <div class="d-flex align-items-center">
      <div class="calendar-circle-small m-0" style="background-color: rgba(27, 187, 164, 0.4);"></div>
      <p class="my-0 mx-1">Work day</p>
    </div>
    <div class="d-flex align-items-center">
      <div class="calendar-circle-small m-0" style="background-color: rgb(254, 214, 72, 0.4);"></div>
      <p class="my-0 mx-1">Rest day</p>
    </div>
    <div class="d-flex align-items-center">
      <div class="calendar-circle-small m-0" style="background-color: rgba(241, 98, 81, 0.4);"></div>
      <p class="my-0 mx-1">On MC</p>
    </div>
  </div>

  <div class="my-3 py-3 bg-white" style="text-align: center; box-shadow: 0 0 15px rgba(0,0,0,0.2);">
    <h5>Salary</h5>

    <% start_date = params[:start_date] %>
    <!-- current month calendar doesnt have 'start_date' in url -->
    <% if start_date %>
      <% start_date_arr = start_date.split('-').map(&:to_i) %>
      <% payslip = @payslips.find_by(month: start_date_arr[1], year: start_date_arr[0]) %>
    <% else %>
      <% payslip = @payslips.find_by(month: Time.now.month, year: Time.now.year) %>
    <% end %>



    <% if payslip %>
      <!-- color font according to whether salary is fully paid -->
      <% if payslip.amount >= @basic_salary %>
        <% amount_color = "text-success"  %>
        <% amount_tooltip = 'Boss no ali-bah-bah! 👍' %>
      <% else %>
        <% amount_color = "text-danger"  %>
        <% amount_tooltip = "<a href='/organisation' class='text-white'>Boss may be underpaying you. Seek help.</a>" %>
      <% end %>

      <% if payslip.payment_method == "bank transfer" %>
        <% method_color = "text-success"  %>
        <% method_tooltip = 'Boss no ali-bah-bah! 👍' %>
      <% else %>
        <% method_color = "text-danger"  %>
        <% method_tooltip = "<a href='/organisation' class='text-white'>Boss must pay by bank transfer. Seek help.</a>" %>
      <% end %>

      <p class="my-0 <%= amount_color %>"
        data-toggle="tooltip" data-placement="top" data-trigger="hover" data-html="true" title="<%= amount_tooltip %>">
        Received $<%= payslip.amount %> <i class="fas fa-info-circle"></i>
      </p>
      <p class="<%= method_color %>"
        data-toggle="tooltip" data-placement="top" data-trigger="hover" data-html="true" title="<%= method_tooltip %>">
        By <%= payslip.payment_method %> <i class="fas fa-info-circle"></i>
      </p>
      <%= link_to "Edit", edit_payslip_path(payslip, month: payslip.month, year: payslip.year), class: "btn btn-primary" %>
    <% else %>
      <p>Not received yet</p>
      <% if start_date %>
        <%= link_to "Add", new_payslip_path(month: start_date_arr[1], year:start_date_arr[0]), class: "btn btn-primary" %>
      <% else %>
        <%= link_to "Add", new_payslip_path, class: "btn btn-primary" %>
      <% end %>
    <% end %>
  </div>
</div>

app/views/pages/files.html.erb
<div class="container scrollable">
  <h1 class="text-center pt-3">Your files</h1>
  <ul class="nav nav-tabs" id="myTab" role="tablist">
    <li class="nav-item">
      <a class="nav-link active" id="worklog-tab" data-toggle="tab" href="#worklog" role="tab" aria-controls="worklog" aria-selected="true">Worklogs</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" id="salary-tab" data-toggle="tab" href="#salary" role="tab" aria-controls="salary" aria-selected="false">Salary</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" id="accident-tab" data-toggle="tab" href="#accident" role="tab" aria-controls="accident" aria-selected="false">Accidents</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" id="contract-tab" data-toggle="tab" href="#contract" role="tab" aria-controls="contract" aria-selected="false">IPA</a>
    </li>
  </ul>
  <div class="tab-content" id="myTabContent">
    <div class="tab-pane fade show active" id="worklog" role="tabpanel" aria-labelledby="worklog-tab">

      <% @workdays.each_pair do |key, value| %>
      <button class="btn btn-secondary btn-block dropdown-toggle file" type="button" data-toggle="collapse" data-target="#<%= key.strftime("%B_%Y") %>" aria-expanded="false" aria-controls="worklog_<%= key.strftime("%B_%Y") %>">
        Worklog for <%= key.strftime("%B, %Y") %>
      </button>
      <div class="collapse" id="<%= key.strftime("%B_%Y") %>">
        <div class="card card-body">
          <%= turbo_frame_tag "worklog_email" do %>
          <div class="container border my-3 py-3">
            <h4>Email log as csv</h4>
            <form action="/workdays/send" method="post" id="log<%= key.strftime("%B_%Y") %>">
              <label for="email">Email address:</label><br>
              <input list="organisations" id="email" name="email" class="w-100" autocomplete="off">
              <datalist id="organisations">
                <option value="sip@mwc.org.sg">Migrant Workers Centre</option>
                <option value="info@mysite.com">SG Accident Help Center</option>
                <option value="info@twc2.org.sg">Transient Workers Count too</option>
                <option value="nurezlia@home.org.sg">HOME</option>
                <option value="info@healthserve.org.sg">Health Serve</option>
              </datalist>
              <input type="hidden" name="log_key" value="<%= key %>">
              <button type="submit" form="log<%= key.strftime("%B_%Y") %>" value="Submit" class="btn btn-success mt-2 text-white">Send Email</button>
            </form>
            <% end %>
          </div>
        </div>
      </div>
      <% end %>

    </div>
    <div class="tab-pane fade" id="salary" role="tabpanel" aria-labelledby="salary-tab">
      <% @payslips.each_with_index do |payslip, index| %>
      <button class="btn btn-secondary btn-block dropdown-toggle file" type="button" data-toggle="collapse" data-target="#payslip_<%= index %>" aria-expanded="false" aria-controls="payslip_<%= index %>">
        <%= Date::MONTHNAMES[payslip.month] %> <%= payslip.year %>
      </button>
      <div class="collapse" id="payslip_<%= index %>">
        <div class="card card-body">
          <p>Amount: <%= payslip.amount  %></p>
          <p>Paid by: <%= payslip.payment_method %></p>
          <div class="d-flex">
            <% payslip.photos.each do |photo| %>
            <%= cl_image_tag photo.key, crop: :fit, class: 'img_preview' %>
            <% end %>
          </div>
          <%= turbo_frame_tag "payslip_email" do %>
          <div class="container border my-3 py-3">
            <h4>Send payslip details as email</h4>
            <form action="/payslips/send" method="post" id="payslip<%= payslip.id %>">
              <label for="email">Email address:</label><br>
              <input list="organisations" id="email" name="email" class="w-100" autocomplete="off">
              <datalist id="organisations">
                <option value="sip@mwc.org.sg">Migrant Workers Centre</option>
                <option value="info@mysite.com">FF</option>
                <option value="info@twc2.org.sg">Transient Workers Count too</option>
                <option value="nurezlia@home.org.sg">HOME</option>
                <option value="info@healthserve.org.sg">Health Serve</option>
              </datalist><br>
              <input type="hidden" name="payslip_id" value="<%= payslip.id %>">
              <button type="submit" form="payslip<%= payslip.id %>" value="Submit" class="btn btn-success mt-2 text-white">Send Email</button>
            </form>
            <% end %>
          </div>
        </div>
      </div>
      <% end %>
    </div>
    <div class="tab-pane fade" id="accident" role="tabpanel" aria-labelledby="accident-tab">
      <% @accidents.each_with_index do |accident, index| %>
      <button class="btn btn-secondary btn-block dropdown-toggle file" type="button" data-toggle="collapse" data-target="#accident_<%= index %>" aria-expanded="false" aria-controls="accident_<%= index %>">
        <%= accident.injured_part %> injury on <%= accident.date.strftime("%d %b %Y") %>
      </button>
      <div class="collapse" id="accident_<%= index %>">
        <div class="card card-body accident">
          <p><strong>Date:</strong><br><%= accident.date.strftime("%d %b %Y") %></p>
          <p><strong>Time:</strong><br><%= accident.time.strftime("%k:%M")%></p>
          <p><strong>Description:</strong><br><%= accident.description%></p>
          <p><strong>Part injured:</strong><br><%= accident.injured_part%></p>
          <p><strong>Place of Treatment:</strong><br><%= accident.medical_facility%><br>
            <% if accident.medical_facility == 'None' || nil %>
            <small class="text-danger">*Boss should have brought you to medical facility*</small>
            <% end %>
          </p>
          <p>
            <strong>Treatment was paid by boss:</strong><br><%= accident.paid_by_employer ? 'Yes' : 'No' %> <br>
            <% unless accident.paid_by_employer %>
            <small class="text-danger">*Boss should have paid*</small>
            <% end %>
          </p>
          <p>
            <strong>No. of MC days:</strong><br><%= accident.mc_days %><br>
            <% if accident.mc_days == 0 || nil %>
            <small class="text-danger">*MC should have been given*</small>
            <% end %>
          </p>
          <p>Attached photos: <%= accident.photos.count %></p>
          <div class="d-flex">
            <% accident.photos.each do |photo| %>
            <%= cl_image_tag photo.key, height: 100, crop: :fit %>
            <% end %>
          </div>

          <%= turbo_frame_tag "email" do %>
          <div class="border p-3 my-3">
            <h4>Send the report as an email</h4>
            <form action="/accidents/send" method="post">
              <label for="email">Email address:</label><br>
              <input list="organisations" id="email" name="email" class="w-100" autocomplete="off">
              <datalist id="organisations">
                <option value="sip@mwc.org.sg">Migrant Workers Centre</option>
                <option value="info@mysite.com">SG Accident Help Center</option>
                <option value="info@twc2.org.sg">Transient Workers Count too</option>
                <option value="nurezlia@home.org.sg">HOME</option>
                <option value="info@healthserve.org.sg">Health Serve</option>
              </datalist><br>
              <input type="hidden" name="accident_id" value="<%= accident.id %>">
              <%= button_to "Send Email", accidents_send_path(@accident), class: 'btn btn-success mt-2 text-white' %>
            </form>
          </div>
          <% end %>
        </div>
      </div>
      <% end %>
    </div>
    <div class="tab-pane fade" id="contract" role="tabpanel" aria-labelledby="contract-tab">
      <div class="py-3">
        <div class="d-flex justify-content-around">
          <% if @user.ipa_photo %>
          <%= cl_image_tag @user.ipa_photo.key, crop: :fit, class: 'img_preview' %>
          <% end %>
        </div>
      </div>
      <%= turbo_frame_tag "ipa_email" do %>
      <div class="container border my-3 py-3">
        <h4>Send IPA as email</h4>
        <form action="/users/send" method="post" id="ipa">
          <label for="email">Email address:</label><br>
          <input list="organisations" id="email" name="email" class="w-100" autocomplete="off">
          <datalist id="organisations">
            <option value="sip@mwc.org.sg">Migrant Workers Centre</option>
            <option value="info@mysite.com">SG Accident Help Centre</option>
            <option value="info@twc2.org.sg">Transient Workers Count too</option>
            <option value="nurezlia@home.org.sg">HOME</option>
            <option value="info@healthserve.org.sg">Health Serve</option>
          </datalist><br>
          <button type="submit" form="ipa" value="Submit" class="btn btn-success mt-2 text-white">Send Email</button>
        </form>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/pages/home.html.erb
<div class="container ">
  <% if @workday_checkedin.nil? %>
  <div class="d-flex parent">
    <div class="card-product mb-3 mt-3 round square">
      <div class="square border-dark round">
        <h5 class= "text-center text-white border-dark square" style="background-color:#262737"><%=  (Date::MONTHNAMES[Date.today.mon]).capitalize%></h5>
        <h1 class= "text-center" style="line-height: 80px"><%=  Date.today.day%></h1>
      </div>
    </div>

    <div class="child" style="float:left;">
      <span class="badge badge-danger badge-customize">!</span>
      <h5>Good evening, <%= current_user.name %>!<br>Please check in! 👇</h5>
    </div>

  </div>
  <strong><%= link_to 'Check in today', new_workday_path,class: "text-white btn btn-warning mb-3 btn-block", style:"box-shadow: 0 0 15px rgba(0,0,0,0.2);
",data: { turbo: 'false' } %></strong>
  <% else %>
  <div class="card-product mb-3 mt-3 ml-1 round square left">
    <div class="square border-dark round">
      <h5 class= "text-center text-white border-dark square" style="background-color:#262737"><%=  (Date::MONTHNAMES[Date.today.mon]).capitalize%></h5>
      <h1 class= "text-center" style="line-height: 80px"><%=  Date.today.day%></h1>
    </div>
  </div>
  <div class="mt-3 text-blue text-center container">
    <% if @workday_checkedin.on_mc %>
    <p class="move-down" style="color:#2ab59b">Get well soon 🙏</p>
    <strong><i class="fas fa-info-circle"></i>
      <%= link_to organisation_path(anchor: "article#{@article.first.id}"), data: { turbo: false } do %><%= @article.first.title %><% end %>
    </strong>
    <% elsif @workday_checkedin.on_rest %>
    <p class="move-down" style="color:#2ab59b">Enjoy your rest day 🤗 </p>
    <strong><i class="fas fa-info-circle"></i>
      <%= link_to organisation_path(anchor: "article#{@article.first.id}"), data: { turbo: false } do %><%= @article.first.title %><% end %>
      <!-- <a href="/organisation#article<%= @article.first.id %>"><%= @article.first.title %></a> -->
    </strong>
    <% else %>
    <strong><p class="move-down" style="color:#2ab59b">You've checked in today! 👍 </p></strong>
    <strong><i class="fas fa-info-circle"></i>
      <%= link_to organisation_path(anchor: "article#{@article.first.id}"), data: { turbo: false } do %><%= @article.first.title %><% end %>
    </strong>
    <% end %>
    <% end %>

  </div>

  <div id="carouselExampleIndicators" class="carousel slide mb-3" data-ride="carousel">
    <ol class="carousel-indicators">
      <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
      <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
      <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
    </ol>
    <div class="carousel-inner" style=" width:100%; height: 200px !important;">
      <div class="carousel-item active">
        <a href="https://www.sgmigrant.com" target="_blank">
          <%= image_tag "case.png", class: "d-block w-100 caro-image" %>
         <div class="carousel-caption">
          <p>One stop portal for COVID-19, mental wellness and recreation</p>
        </div>
      </a>
    </div>
    <div class="carousel-item">
     <a href="https://www.youtube.com/watch?v=W9NqBtOaeUs" target="_blank">
      <%= image_tag "Bengali-image.png", class: "d-block w-100 caro-image" %>
      <div class="carousel-caption">
        <p>Get your questions about policy changes during COVID-19 answered (bengali only)</p>
      </div>
    </a>
  </div>
     <div class="carousel-item">
      <a href="https://www.globalmigrantfestival.com/sgmigrantpoetry" target="_blank">
        <%= image_tag "migrant-worker-poetry.png", class: "d-block w-100 caro-image" %>
      </a>
    </div>
</div>
<a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
  <span class="carousel-control-prev-icon" aria-hidden="true"></span>
  <span class="sr-only">Previous</span>
</a>
<a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
  <span class="carousel-control-next-icon" aria-hidden="true"></span>
  <span class="sr-only">Next</span>
</a>
</div>
</div>
<div style="background-color:#262737" class="py-4 mb-5">
  <div class="container">
    <%= link_to new_workday_path do %>
      <div class="card-product-home my-3 p-3 rounded">
        <%= image_tag "card-forgot.png", height: 61, width: 61, crop: :fill %>
        <div class="card-product-infos">
          <h2>Forgot to check in?</h2>
          <div class="card-line" style="height: 2px; background-color:#1bbba4"></div>
          <p>Log your hours for a missed day so that your boss cannot underpay you. &rarr; </p>
        </div>
      </div>
    <% end %>

    <%= link_to new_accident_path do %>
      <div class="card-product-home my-3 p-3 rounded">
        <%= image_tag "card-accident.png", height: 61, width: 61, crop: :fill %>
        <div class="card-product-infos">
          <h2>Accident at work?</h2>
          <div class="card-line" style="height: 2px; background-color:#1bbba4"></div>
          <p>Let us automate the medical reporting process and keep your paperwork organised. &rarr;</p>
        </div>
      </div>
    <% end %>

    <%= link_to new_payslip_path do %>
      <div class="card-product-home my-3 p-3 rounded">
        <%= image_tag "card-paid.png", height: 61, width: 61, crop: :fill %>
        <div class="card-product-infos">
          <h2>Got paid?</h2>
          <div class="card-line" style="height: 2px; background-color:#1bbba4"></div>
          <p>Log your salary so that we can check that you are being paid fairly and on time. &rarr;</p>
        </div>
      </div>
    <% end %>
    <br>
    <% if user_signed_in? %>
    <%= button_to "More options >", destroy_user_session_path, method: :delete, class: "btn btn-outline-primary text-white", style: "font-size:15px; margin-left:105px;",data: { turbo: false }  %>
    <% end %>
  </div>
</div>

app/views/pages/landing.html.erb
<div class="container my-4">
    <%= image_tag "boss-abb-logo.png", height: 80, width: 80, crop: :fill, id: 'logo' %>
  <div id="carouselLanding" class="carousel slide mb-4" data-ride="carousel" data-interval="3000">
    <ol class="carousel-indicators">
      <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
      <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
      <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
    </ol>
    <div class="carousel-inner">
      <div class="carousel-item active">
        <%= image_tag "landing-contract.svg" %>
        <div class="carousel-caption">
          <h5>Learn about your employment rights</h5>
        </div>
      </div>
      <div class="carousel-item">
        <%= image_tag "landing-documents.svg" %>
        <div class="carousel-caption">
          <h5>Protect yourself with simple records</h5>
        </div>
      </div>
      <div class="carousel-item">
        <%= image_tag "landing-sign.svg" %>
        <div class="carousel-caption">
          <h5>Seek help easily</h5>
        </div>
      </div>
    </div>
    <a class="carousel-control-prev" href="#carouselLanding" role="button" data-slide="prev">
      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
      <span class="sr-only">Previous</span>
    </a>
    <a class="carousel-control-next" href="#carouselLanding" role="button" data-slide="next">
      <span class="carousel-control-next-icon" aria-hidden="true"></span>
      <span class="sr-only">Next</span>
    </a>
  </div>
  <%= link_to "Sign Up", new_user_registration_path, class: 'btn btn-block btn-blue mt-4 text-white', data: { turbo: false }  %>
  <%= link_to "Log In", new_user_session_path, class: 'btn btn-block btn-outline-primary mt-2 mb-4 text-primary', data: { turbo: false }  %>
</div>