config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: "registrations" }

  root to: 'pages#home'
  get '/calendar', to: 'pages#calendar'

  get '/accidents/confirm', to: 'accidents#confirm'
  post '/accidents/send', to: 'accidents#send_accident'
  post '/workdays/send', to: 'workdays#send_worklog'
  post '/payslips/send', to: 'payslips#send_payslip'
  post '/users/send', to: 'users#send_ipa'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :accidents do
    member do
      get :new3
      get :complete
    end
  end

  get '/onboarding', to: 'users#onboarding', as: 'onboarding'
  get '/landing', to: 'pages#landing'
  patch '/contract_update', to: 'users#contract_update', as: 'contract_update'
  get '/personal_details', to: 'users#personal_details', as: 'personal_details'
  patch '/personal_update', to: 'users#personal_update', as: 'personal_update'
  resources :users
  resources :workdays, only: [:new, :create, :edit, :update]
  get 'workdays/on_leave', to: 'workdays#on_leave'
  get 'workdays/on_leave/:id', to: 'workdays#on_leave'
  get 'workdays/working/:id', to: 'workdays#working'
  get 'organisation', to: 'organisations#index'
  get 'faq', to: 'organisations#faq'
  resources :payslips, only: [:new, :create, :edit, :update]
  get '/files', to: 'pages#files'
end

app/models/accident.rb
class Accident < ApplicationRecord
  belongs_to :user
  has_many :workdays
  has_many_attached :photos
  has_one_attached :audio

  validates :description, presence: true
end

app/controllers/accidents_controller.rb
class AccidentsController < ApplicationController
  def new
    # check if current_user last accident is 10 mins ago
    if session[:accident].nil?
      @accident = Accident.new
    else
      @accident = Accident.find(session[:accident])
    end
  end

  def create
    @accident = Accident.new(accident_params)
    @accident.user = current_user
    if @accident.save
      session[:accident] = @accident.id
      redirect_to edit_accident_path(@accident)
    else
      render :new
    end
  end

  def edit
    @accident = Accident.find(params[:id])
  end

  def update
    @accident = Accident.find(params[:id])
    if @accident.update!(accident_params)
      if accident_params[:date]
        @hospitals = ['Alexandria Hospital', 'Changi General Hospital', 'Khoo Teck Puat Hospital', 'National Skin Centre', 'National University Hospital', 'Ng Teng Fong General Hospital', 'Singapore General Hospital', 'Singapore National Eye Centre', 'Tan Tock Seng Hospital']
        redirect_to edit_accident_path(@accident)
      elsif accident_params[:injured_part]
        redirect_to new3_accident_path(@accident)
      else
        redirect_to complete_accident_path(@accident)
      end
    else
      render :edit
    end
  end

  def new3
    @accident = Accident.find(params[:id])
  end

  def complete
    @accident = Accident.find(params[:id])
  end

  def send_accident
    @user = current_user
    @accident = Accident.find(email_params[:accident_id].to_i)
    @recipient = email_params[:email]
    if email_params[:email].match(/\A([\w+\-].?)+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i)
      UserMailer.with(user: @user, accident: @accident, recipient: @recipient).send_accident.deliver_now
    else
      render :complete
    end
  end

  def confirm
    session[:accident] = nil
    redirect_to root_path
  end

  private

  def accident_params
    params.require(:accident).permit(:date, :time, :description, :injured_part, :medical_facility, :paid_by_employer, :mc_days, photos: [])
  end

  def email_params
    params.permit(:email, :accident_id)
  end
end

app/views/accidents/complete.html.erb
<%= turbo_frame_tag :accident do %>
<div class="accident">
  <h2>Review your information</h2>
  <p><strong>Date:</strong><br><%= @accident.date.strftime("%d %b %Y") %></p>
  <p><strong>Time:</strong><br><%= @accident.time.strftime("%k:%M")%></p>
  <p><strong>Description:</strong><br><%= @accident.description%></p>
  <p><strong>Part injured:</strong><br><%= @accident.injured_part%></p>
  <p><strong>Place of Treatment:</strong><br><%= @accident.medical_facility%><br>
    <% if @accident.medical_facility == 'None' || nil %>
    <small class="text-danger">*Boss should have brought you to medical facility*</small>
    <% end %>
  </p>
  <p>
    <strong>Treatment was paid by boss:</strong><br><%= @accident.paid_by_employer ? 'Yes' : 'No' %> <br>
    <% unless @accident.paid_by_employer %>
    <small class="text-danger">*Boss should have paid*</small>
    <% end %>
  </p>
  <p>
    <strong>No. of MC days:</strong><br><%= @accident.mc_days %><br>
    <% if @accident.mc_days == 0 || nil %>
    <small class="text-danger">*MC should have been given*</small>
    <% end %>
  </p>
  <p>Attached photos: <%= @accident.photos.count %></p>
  <div class="d-flex">
    <% @accident.photos.each do |photo| %>
    <%= cl_image_tag photo.key, crop: :fit, height: 100 %>
    <% end %>
  </div>
</div>
<%= turbo_frame_tag "email" do %>
<div class="container py-3 my-3 border rounded bg-white">
  <h4>Send the report as an email</h4>
  <form action="/accidents/send" method="post">
    <label for="email">Email address:</label><br>
    <input list="organisations" id="email" name="email" class="w-100" autocomplete="off">
    <datalist id="organisations">
      <option value="sip@mwc.org.sg">Migrant Workers Centre</option>
      <option value="info@mysite.com">SG Accident Help Centre</option>
      <option value="info@twc2.org.sg">Transient Workers Count too</option>
      <option value="nurezlia@home.org.sg">HOME</option>
      <option value="info@healthserve.org.sg">Health Serve</option>
    </datalist><br>
    <input type="hidden" name="accident_id" value="<%= @accident.id %>">
    <%= button_to "Send Email", accidents_send_path(@accident), class:'btn btn-success mt-2 text-white' %>
  </form>
</div>
<% end %>

<%= link_to 'Confirm and go to home', accidents_confirm_path, class: 'btn btn-block btn-primary', data: { turbo: false }  %>
<%= link_to "Edit", new3_accident_path(@accident), class: 'btn btn-block btn-warning mb-3' %>
<% end %>

app/views/accidents/edit.html.erb
<%= turbo_frame_tag "accident" do %>
<div class="bg-secondary mt-3 mb-5 d-flex w-100 justify-content-between align-items-center" style="height:5px">
  <div class="btn-green rounded-circle text-center" style="height: 50px; width: 50px; line-height: 50px">
    <p class="align-middle text-white">1</p>
  </div>
  <div class="btn-green rounded-circle text-center" style="height: 50px; width: 50px; line-height: 50px">
    <p class="text-white">2</p>
  </div>
  <div class="bg-dark rounded-circle text-center" style="height: 50px; width: 50px; line-height: 50px">
    <p class="text-secondary">3</p>
  </div>
</div>
<div class="container">
  <%= simple_form_for @accident do |f| %>
    <label class="string optional" for="accident_injured_part">Injured part</label>
    <input class="form-control string optional" list="parts" name="accident[injured_part]" id="accident_injured_part" autocomplete="off">
    <datalist id="parts">
      <option value="Head"></option>
      <option value="Shoulders"></option>
      <option value="Knees"></option>
      <option value="Toes"></option>
      <option value="Eyes"></option>
    </datalist>
    <%= f.input :medical_facility, as: :select, collection: ['None', 'Alexandria Hospital', 'Changi General Hospital', 'Khoo Teck Puat Hospital', 'National Skin Centre', 'National University Hospital', 'Ng Teng Fong General Hospital', 'Singapore General Hospital', 'Singapore National Eye Centre', 'Tan Tock Seng Hospital'] %>
    <%= f.submit 'Next', class: 'btn btn-block btn-primary mb-3' %>
  <% end %>
  <%= link_to "Back", new_accident_path(accident: @accident), class: 'btn btn-block btn-warning' %>
  </div>
<% end %>

app/views/accidents/new.html.erb
<div class="container pt-3 scrollable">
  <%= turbo_frame_tag "accident" do %>
    <div class="bg-secondary mt-3 mb-4 d-flex w-100 justify-content-between align-items-center" style="height:5px">
      <div class="btn-green rounded-circle text-center" style="height: 50px; width: 50px; line-height: 50px">
        <p class="align-middle text-white">1</p>
      </div>
      <div class="bg-dark rounded-circle text-center" style="height: 50px; width: 50px; line-height: 50px">
        <p class="text-secondary">2</p>
      </div>
      <div class="bg-dark rounded-circle text-center" style="height: 50px; width: 50px; line-height: 50px">
        <p class="text-secondary">3</p>
      </div>
    </div>
  <div class="pt-2">
    <%= simple_form_for @accident do |f| %>
    <%= f.input :date, label: 'Date of Accident', as: :string, type: :text %>
    <%= f.input :time, label: 'Time of Accident', as: :time, minute_step: 5 %>
    <%= f.input :description, label: 'What happened?', input_html: { rows: 10, onfocus: " let value = this.value; this.value = null; this.value=value" }, as: :text %>
    <%= f.submit 'Next', class: 'btn btn-primary btn-block' %>
    <% end %>
    <% end %>
  </div>
  <div class="modal fade" id="accidentModal" tabindex="-1" aria-labelledby="accidentModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="accidentModalLabel">Quick input</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body  mx-auto">
          <button type="button" class="btn btn-primary my-1 w-100 accident-type" data-toggle="modal" data-target="#accidentModal">
            Fell Down
          </button><br>
          <button type="button" class="btn btn-primary my-1 w-100 accident-type" data-toggle="modal" data-target="#accidentModal">
            Hit by object
          </button><br>
          <button type="button" class="btn btn-primary my-1 w-100 accident-type" data-toggle="modal" data-target="#accidentModal">
            Crushed by machine
          </button><br>
          <button type="button" class="btn btn-primary my-1 w-100 accident-type" data-toggle="modal" data-target="#accidentModal">
            Burned
          </button><br>
          <button type="button" class="btn btn-primary my-1 w-100 accident-type" data-toggle="modal" data-target="#accidentModal">
            Electrocuted
          </button>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/accidents/new3.html.erb
<%= turbo_frame_tag "accident" do %>
<div class="bg-secondary mt-3 mb-5 d-flex w-100 justify-content-between align-items-center" style="height:5px">
  <div class="btn-green rounded-circle text-center" style="height: 50px; width: 50px; line-height: 50px">
    <p class="align-middle text-white">1</p>
  </div>
  <div class="btn-green rounded-circle text-center" style="height: 50px; width: 50px; line-height: 50px">
    <p class="text-white">2</p>
  </div>
  <div class="btn-green rounded-circle text-center" style="height: 50px; width: 50px; line-height: 50px">
    <p class="text-white">3</p>
  </div>
</div>
<%= simple_form_for @accident do |f| %>
<%= f.input :paid_by_employer, as: :select, label: 'Did boss pay?' %>
<%= f.input :mc_days %>
<%= f.input :photos, as: :file, input_html: { multiple: true } %>
<%= f.submit 'Finish', class: 'btn btn-primary btn-block mb-3' %>
<% end %>
<%= link_to "Back", edit_accident_path(@accident), class: 'btn btn-block btn-warning' %>
<% end %>

app/views/accidents/send_accident.html.erb
<%= turbo_frame_tag "email" do %>
<div class="container border my-3 py-3">
  <h4>Send the report as an email</h4>
  <p>Email is on its way!</p>
</div>
<% end %>